spring.application.name=Laboratorio01

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_postucr
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Configurar thymeleaf
spring.thymeleaf.cache=false
spring.devtools.restart.enabled=false

#Password
app.jwt.secret=Estoesunaclavebienseguraquemasadelantevamosausar
app.jwt.expiration=3600000